map_type: costmap

obstacle_range: 2.5
raytrace_range: 3

transform_tolerance: 5

robot_radius: 0.0
inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
